name: CI

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: ubuntu-24.04
            compiler: gcc
            cc: gcc-14
            cxx: g++-14
          - os: ubuntu-24.04
            compiler: clang
            cc: clang-18
            cxx: clang++-18
          - os: windows-latest
            compiler: msvc
            cc: cl
            cxx: cl
          - os: windows-latest
            compiler: clang-cl
            cc: clang-cl
            cxx: clang-cl
    steps:
        - uses: actions/checkout@v4

        - name: Install GCC (Linux)
          if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'gcc'
          run: |
            sudo apt update
            sudo apt install -y gcc-14 g++-14
        - name: Install Clang (Linux)
          if: matrix.os == 'ubuntu-24.04' && matrix.compiler == 'clang'
          run: |
            sudo apt update
            sudo apt install -y clang-19 libstdc++-14-dev

        - name: Configure (Linux)
          if: runner.os == 'Linux'
          env:
            CC: ${{ matrix.cc }}
            CXX: ${{ matrix.cxx }}
          run: |
            cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON
        - name: Configure (Windows) (Clang)
          if: runner.os == 'windows-latest' && matrix.compiler == 'clang'
          run: |
            cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON \
            -T ClangCL
        - name: Configure (Windows) (MSVC)
          if: runner.os == 'windows-latest' && matrix.compiler == 'msvc'
          run: |
            cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTS=ON
        - name: Build
          run: cmake --build build --config Debug --parallel
        - name: Test
          run: ctest --test-dir build -C Debug --output-on-failure --parallel 4